theme: jekyll-theme-cayman
logo: /assets/img/logo-reverse.png
title: " "
show_downloads: false
google_analytics: 00000001
url:     "https://test.palmerit.co/"
github_username: toloco



# Optional features
show_related_posts:   True
show_post_footers:    True
show_social_icons:    True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true


