theme: jekyll-theme-minimal
logo: /assets/img/logo.png
title: [The title of your site]
description: [A short description of your site's purpose]
show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]


github:
  zip_url: http://example.com/download.zip
  another_url: another value

github_username: toloco



# Optional features
show_related_posts:   True
show_post_footers:    True
show_social_icons:    True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true


url:     "https://palmerit.co/"